Add smart case function
IngoMeyer441/zsh-easy-motion pull request #4
Opened 2023-01-21 15:16 UTC by cychen2021

When the option EASY_MOTION_SMART_CASE on, the plugin will match both the original lower case letter and the corresponding upper case letter if a lower case letter is provided.

It is just like the smart case option for the original vim easymotion plugin.

2023-01-27 13:25 UTC, IngoMeyer441 requested changes
Thanks for your PR! I have some minor issues. Would be great if you could look into this before the PR is merged.

2023-01-27 13:25 UTC, IngoMeyer441 commented on easy_motion.py
> +                    if not PY2 and smart_case and motion_argument is not None and motion_argument.islower():
Why is Python 2 excluded? `chain` is also [available in Python 2](https://docs.python.org/2.7/library/itertools.html#itertools.chain).

2023-01-27 13:25 UTC, IngoMeyer441 commented on easy_motion.py
> +                      indices = chain(motion_to_indices(cursor_position, text, motion, motion_argument), motion_to_indices(cursor_position, text, motion, motion_argument.upper()))
It is correct to put both results together, but the order of assigned target keys won't be in the correct order. `motion_to_indices` sorts the results by the distance from the current cursor position. IMHO, the results of both calls should be merged together to preserve the order or the regular expressions in `motion_to_indices` should be used with the case-insensitive option, which is probably easier.

2023-01-28 08:33 UTC, cychen2021 commented on easy_motion.py
> +                    if not PY2 and smart_case and motion_argument is not None and motion_argument.islower():
It's a mistake. I'm unfamiliar with Python 2 and thought it didn't supported this. I'll fix it.

2023-01-28 08:34 UTC, cychen2021 commented on easy_motion.py
> +                      indices = chain(motion_to_indices(cursor_position, text, motion, motion_argument), motion_to_indices(cursor_position, text, motion, motion_argument.upper()))
I'll fix this in later commits/

2023-01-30 12:21 UTC, cychen2021 commented
Ready for review @IngoMeyer441

2023-01-31 09:01 UTC, IngoMeyer441 commented
Thank you very much for your contribution, looks good to me!

2023-01-31 09:01 UTC, merged